language: cpp
sudo: false

os:
- linux
- osx
- windows

script: |
  case "${TRAVIS_OS_NAME}" in
    linux)
      make mergJSON-x64.so
    ;;
    osx)
      xcodebuild -configuration Debug -scheme mergJSON-OSX -target mergJSON-OSX -UseModernBuildSystem=NO build
    ;;
    windows)
      export MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      export PATH=$MSBUILD_PATH:$PATH
      MSBuild.exe "mergJSON\mergJSON.sln" //fl //flp:Verbosity=normal //nologo //m:1 //p:Configuration=Debug //p:Platform=x64
    ;;
  esac


# deploy:
#   provider: releases
#   api_key:
#     secure: yiehaOI6VhmgYNvVUml+i6G1dmpTcHaHdbGb/jyUgMSFjvX6REnzurC3DFlvpUxGcxOFsZ5v8U0JFazBnmpRfTohXEyVkrp0tr98l2E3/s+xycircXChvUxMbMElMbNgau970cNV1rkHWMjCaIVRnySeWtuc2+67wFWoWyBUECRkGq2HWrQvUGFMUuBRUYOCrBMd7VIzA4yrH3NXgd84dmyy2JCOJQbaCm+g4x0GjcdESXr0SmQWX8egqFro5n+HDsDh9yhD0dE7rNc0RAuckc23ZAipQpYToNAA55CT3R8wQLTRr4Wt4MCg6SAVpp5r7bLCDpdNTz8arovlQqgErasS/wsYWWTllebTRm3aG/uh/V18qQd6gXdvguuhcR5PUa4rjt6Ww+iq+Y5A/Nf0XN0ZKkjoLLTEQpFgt5NLCKvK1l+sVc3vR9Ebfp6hpVOjvjY6eCd7fBD9unTVRQapINP66yWL85qZYEiyYbIfHkCO4yrhq7Pbhr+0EOrWmJZSYOZ7rkeoQw0B148lktaT6MPtc8f7cdoV3iGVS2bulsf414AovHL3NxUiI9PlKqd5St4IfBIFQu6AtvaOHxDZmXTSkkXyi39yaQXEc9vp2sd74+ZR+SXqoDcZA5Fa+eln3EJyVaZLp69H2WyqFuasD+CrCOpscF3fM+Cw9MakHc0=
#   file: build/mergJSON-x64.so
#   on:
#     repo: montegoulding/mergJSON
#     tags: true
